theme = "everforest_light_modded"

[editor]
line-number = "relative"
cursor-shape.insert = "bar"
insert-final-newline = false
# rulers = [80, 100]
true-color = true

[editor.whitespace.render]
tab = "all"
# space = "all"

[editor.indent-guides]
render = true
character = "â¸½"

[editor.soft-wrap]
wrap-at-text-width = true

[editor.lsp]
display-inlay-hints = true

[keys.normal]
"_" = ["extend_line_up", "extend_to_line_bounds"]
"+" = ["extend_line_down", "extend_to_line_bounds"]

[keys.normal.g]
"b" = ":echo git show %sh{git blame -L %{cursor_line},+1 %{buffer_name} | awk '{print $1}'}"

[keys.normal.z]
s = ":set soft-wrap.enable true"
S = ":set soft-wrap.enable false"
